version: '3.9'

services:
    dataset-explorer-migration:
        build:
            dockerfile: Dockerfile
            context: .
            target: execute-migration
        networks:
            - database
        environment:
            DATABASE_HOST: database
            DATABASE_USERNAME: postgres
            DATABASE_PASSWORD: password
            DATABASE_SCHEMA: dataset-explorer

networks:
    database:
        name: database
        driver: bridge
        external: true